server {
    listen 80;
    server_name _;
    return 444;
}

server {
	listen 443 ssl;
	ssl_protocols TLSv1.2 TLSv1.3;
		
	server_name localhost mzouine.42.fr www.mzouine.42.fr; # the domains nginx responds to

	ssl_certificate_key /etc/nginx/ssl/nginx.key;
	ssl_certificate /etc/nginx/ssl/nginx.crt;

	root /var/www/wordpress; # sets the base folder on disk where Nginx looks for files
	index index.php index.html index.htm; # tells Nginx which file to serve when a directory is requested

		
	location / {
		try_files $uri $uri/ =404;
		# it search for the requested file using the name either as a file or as a directory that has index.html / returns 404 if it didn´t find anything
	}

	location ~ \.php$ {
		include snippets/fastcgi-php.conf; # tells Nginx how to translate a request URL into a real PHP file path
		include fastcgi_params; # tells Nginx which request metadata to pass to PHP-FPM
		fastcgi_pass wordpress:9000;
	}
}
