server {
    listen 80;
    server_name _;
    return 444;
}

server {
	listen 443 ssl;
	ssl_protocols TLSv1.2 TLSv1.3;
		
	server_name localhost mzouine.42.fr www.mzouine.42.fr; # the domains nginx responds to

	ssl_certificate_key /etc/nginx/ssl/nginx.key;
	ssl_certificate /etc/nginx/ssl/nginx.crt;

	root /var/www/wordpress;
	index index.php index.html index.htm;

		
	location / {
		try_files $uri $uri/ =404;
		#it search for the requested file using the name either as a file or as a directory that has index.html
	}

	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass wordpress:9000;
	}
}
