services:
  nginx:
    build: requirements/nginx/
    image: nginx:inception
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/wordpress
    networks:
     - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    image: wordpress:inception
    env_file:
      - ./.env
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/wordpress
    networks:
     - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    image: mariadb:inception
    env_file:
      - ./.env
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
     - inception
    restart: always

volumes:
  wordpress_volume:
    driver: local #use default local volume driver
    driver_opts:
      type: 'none' #don't try to create, format, or manage a filesystem
      o: 'bind' #enables a bind mount, creating a direct link between a directory inside the container and a directory on the host machine
      device: '/home/mzouine/data/wordpress'
  mariadb_volume:
    driver: local #use default local volume driver
    driver_opts:
      type: 'none'
      o: 'bind' 
      device: '/home/mzouine/data/mariadb'
networks:
  inception:
    driver: bridge #Containers can talk to each other by service name
                   #Containers are isolated from the host and other Docker networks
                   #Docker handles internal DNS automatically