services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"  # NOT SURE OF THIS! CHECK IT LATER ON !
    depends_on:
      - wordpress

  wordpress:
    build: requirements/wordpress/
    depends_on:
      - mariadb

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
